### ISSUE TITLE
BlindBidProof functional implementation

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-blindbid#4]
We need to develop the blindbidproof builder library.
To do so, we will need to:
- [ ] Implement BlindBid functional impl #3
- [x] Implement Bid structure logic #1 
- [x] Implement Bid encoding into `Scalar` to insert in in a Kelvin Tree #5 
- [ ] Implement unit tests for blindbid proofs 
- [ ] Implement Score generation function  #6

**Comment by CPerezz** [comment]
This is currently blocking the full development/testing of the BlindBid Contract.

It is blocked by: https://github.com/dusk-network/Poseidon252/issues/7
